service: thoughtofyoucoapi

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: dev
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

functions:
  app:
    handler: build/index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
