org: cgarrovillo
app: thoughtofyouco
service: thoughtofyoucoapi

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  memorySize: 512
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
    resourcePolicy:
      - Effect: Deny
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*
        Condition:
          NotIpAddress:
            aws:SourceIp:
              - 2604:3d09:1c74:5500:85bf:a120:75c8:4e6a
              - 96.51.165.91
      - Effect: Allow
        Principal: '*'
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*/*/*

  environment:
    MONGODB_URI: ${ssm:MONGODB_URI}
    STRIPE_RESTRICTED_KEY: ${ssm:STRIPE_RESTRICTED_KEY}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

functions:
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
  getAllProducts:
    handler: build/index.handler
    events:
      - http:
          path: /${opt:stage}/v1/products
          method: GET
