service: thoughtofyoucoapi

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  app:
    handler: build/index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
