org: cgarrovillo
app: thoughtofyouco
service: thoughtofyoucoapi

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
  memorySize: 512
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    MONGODB_URI: ${ssm:MONGODB_URI}
    STRIPE_RESTRICTED_KEY: ${ssm:STRIPE_RESTRICTED_KEY}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

functions:
  authorizerFunc:
    handler: build/auth.handler
  app:
    handler: build/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
          authorizer: authorizerFunc
  getAllProducts:
    handler: build/index.handler
    events:
      - http:
          path: /${opt:stage}/v1/products
          method: GET
