org: cgarrovillo
app: thoughtofyouco
service: thoughtofyoucoapi

useDotenv: true

provider:
  name: aws
  endpointType: aws
  vpcEndpointIds:
    - vpce-039515c4a706c8278
  runtime: nodejs12.x
  memorySize: 512
  region: us-west-2
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  environment:
    MONGODB_URI: ${ssm:MONGODB_URI}
    STRIPE_RESTRICTED_KEY: ${ssm:STRIPE_RESTRICTED_KEY}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001

functions:
  app:
    handler: build/index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
